// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repositories.Models;

public partial class Account
{
    [Key]
    public int AccountId { get; set; }

    public string UserName { get; set; }

    public string PassWord { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public string AvatarUrl { get; set; }
    public virtual Company Company { get; set; }
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
    public virtual ICollection<StationStaff> StationStaffs { get; set; } = new List<StationStaff>();
}