// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Booking
{
    public int BookingId { get; set; }
    public int CustomerId { get; set; }
    public int VehicleId { get; set; }
    public int PortId { get; set; }
    public DateTime? StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public decimal? Price { get; set; } // Giá đặt lịch (Booking)
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public string Status { get; set; }

    public virtual ChargingSession ChargingSession { get; set; }
    public virtual Customer Customer { get; set; }
    public virtual Port Port { get; set; }
    public virtual Vehicle Vehicle { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}
