// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChargingSession
{
    public int ChargingSessionId { get; set; }
    public int BookingId { get; set; }
    public int CustomerId { get; set; }
    public int VehicleId { get; set; }
    public int PortId { get; set; }
    public int PricingRuleId { get; set; } // Liên kết tới PricingRule

    public int? StartSoc { get; set; }
    public int? EndSoc { get; set; }
    public decimal? EnergyKwh { get; set; }
    public decimal? Subtotal { get; set; }
    public decimal? Tax { get; set; }
    public decimal? Total { get; set; }

    public int? DurationMin { get; set; }
    public int? IdleMin { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? EndedAt { get; set; }
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public string Status { get; set; }

    public virtual Booking Booking { get; set; }
    public virtual Customer Customer { get; set; }
    public virtual Invoice Invoice { get; set; }
    public virtual Port Port { get; set; }
    public virtual Vehicle Vehicle { get; set; }
    public virtual PricingRule PricingRule { get; set; }
}
