// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Charger
{
    public int ChargerId { get; set; }

    public int StationId { get; set; }

    public string Code { get; set; }

    public string Type { get; set; }

    public decimal? PowerKw { get; set; }

    public string Status { get; set; }

    public DateTime? InstalledAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Port> Ports { get; set; } = new List<Port>();
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual Station Station { get; set; }
}