// <auto-generated> Updated and standardized by ChatGPT Assistant </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models
{
    public partial class ChargeStationContext : DbContext
    {
        public ChargeStationContext(DbContextOptions<ChargeStationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Charger> Chargers { get; set; }
        public virtual DbSet<ChargingSession> ChargingSessions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<PricingRule> PricingRules { get; set; }
        public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // 🔥 Map các bảng về đúng tên thật trong SQL
            modelBuilder.Entity<Account>().ToTable("Account");
            modelBuilder.Entity<Booking>().ToTable("Booking");
            modelBuilder.Entity<Charger>().ToTable("Charger");
            modelBuilder.Entity<ChargingSession>().ToTable("ChargingSession");
            modelBuilder.Entity<Company>().ToTable("Company");
            modelBuilder.Entity<Customer>().ToTable("Customer");
            modelBuilder.Entity<Invoice>().ToTable("Invoice");
            modelBuilder.Entity<Payment>().ToTable("Payment");
            modelBuilder.Entity<Port>().ToTable("Port");
            modelBuilder.Entity<Station>().ToTable("Station");
            modelBuilder.Entity<Vehicle>().ToTable("Vehicle");
            modelBuilder.Entity<PricingRule>().ToTable("PricingRules");
            modelBuilder.Entity<SubscriptionPlan>().ToTable("SubscriptionPlan");
            modelBuilder.Entity<Subscription>().ToTable("Subscription");

            #region Account
            modelBuilder.Entity<Account>(entity =>
            {
                entity.HasKey(e => e.AccountId);
                entity.Property(e => e.UserName).IsRequired().HasMaxLength(100);
                entity.Property(e => e.PassWord).IsRequired().HasMaxLength(255);
                entity.Property(e => e.Role).HasMaxLength(30);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.AvatarUrl).HasMaxLength(255);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
            });
            #endregion

            #region Booking
            modelBuilder.Entity<Booking>(entity =>
            {
                entity.HasKey(e => e.BookingId);
                entity.Property(e => e.StartTime).HasColumnType("datetime");
                entity.Property(e => e.EndTime).HasColumnType("datetime");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Pending");
                entity.Property(e => e.Price).HasColumnType("decimal(12,2)");

                entity.HasOne(d => d.Customer).WithMany(p => p.Bookings)
                    .HasForeignKey(d => d.CustomerId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Port).WithMany(p => p.Bookings)
                    .HasForeignKey(d => d.PortId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                    .HasForeignKey(d => d.VehicleId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });
            #endregion

            #region Charger
            modelBuilder.Entity<Charger>(entity =>
            {
                entity.HasKey(e => e.ChargerId);
                entity.Property(e => e.Code).HasMaxLength(50);
                entity.Property(e => e.Type).HasMaxLength(50);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.ImageUrl).HasMaxLength(255);
                entity.Property(e => e.PowerKw).HasColumnType("decimal(6,2)");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");

                entity.HasOne(d => d.Station).WithMany(p => p.Chargers)
                    .HasForeignKey(d => d.StationId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });
            #endregion

            #region ChargingSession
            modelBuilder.Entity<ChargingSession>(entity =>
            {
                entity.HasKey(e => e.ChargingSessionId);
                entity.Property(e => e.StartedAt).HasColumnType("datetime");
                entity.Property(e => e.EndedAt).HasColumnType("datetime");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.EnergyKwh).HasColumnType("decimal(10,2)");
                entity.Property(e => e.Subtotal).HasColumnType("decimal(12,2)");
                entity.Property(e => e.Tax).HasColumnType("decimal(12,2)");
                entity.Property(e => e.Total).HasColumnType("decimal(12,2)");
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");

                entity.HasOne(d => d.Booking).WithOne(p => p.ChargingSession)
                    .HasForeignKey<ChargingSession>(d => d.BookingId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Customer).WithMany(p => p.ChargingSessions)
                    .HasForeignKey(d => d.CustomerId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Port).WithMany(p => p.ChargingSessions)
                    .HasForeignKey(d => d.PortId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Vehicle).WithMany(p => p.ChargingSessions)
                    .HasForeignKey(d => d.VehicleId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.PricingRule).WithMany(p => p.ChargingSessions)
                    .HasForeignKey(d => d.PricingRuleId)
                    .OnDelete(DeleteBehavior.Restrict);

                entity.HasOne(d => d.Invoice).WithMany(p => p.ChargingSessions)
                    .HasForeignKey(d => d.InvoiceId)
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("FK_ChargingSession_Invoice");
            });
            #endregion

            #region Company
            modelBuilder.Entity<Company>(entity =>
            {
                entity.HasKey(e => e.CompanyId);
                entity.Property(e => e.Name).HasMaxLength(200);
                entity.Property(e => e.Address).HasMaxLength(255);
                entity.Property(e => e.Phone).HasMaxLength(20);
                entity.Property(e => e.Email).HasMaxLength(100);
                entity.Property(e => e.ImageUrl).HasMaxLength(255);
                entity.Property(e => e.TaxCode).HasMaxLength(50);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
            });
            #endregion

            #region Customer
            modelBuilder.Entity<Customer>(entity =>
            {
                entity.HasKey(e => e.CustomerId);
                entity.Property(e => e.FullName).HasMaxLength(200);
                entity.Property(e => e.Phone).HasMaxLength(20);
                entity.Property(e => e.Address).HasMaxLength(255);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");

                entity.HasOne(d => d.Account).WithMany(p => p.Customers)
                    .HasForeignKey(d => d.AccountId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Company).WithMany(p => p.Customers)
                    .HasForeignKey(d => d.CompanyId);
            });
            #endregion

            #region Invoice
            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.HasKey(e => e.InvoiceId);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Unpaid");
                entity.Property(e => e.Subtotal).HasColumnType("decimal(12,2)");
                entity.Property(e => e.SubscriptionAdjustment).HasColumnType("decimal(12,2)");
                entity.Property(e => e.Tax).HasColumnType("decimal(12,2)");
                entity.Property(e => e.Total).HasColumnType("decimal(12,2)");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");

                entity.HasOne(d => d.Subscription)
                    .WithMany(p => p.Invoices)
                    .HasForeignKey(d => d.SubscriptionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Invoice_Subscription");
            });
            #endregion

            #region Subscription
            modelBuilder.Entity<Subscription>(entity =>
            {
                entity.HasKey(e => e.SubscriptionId);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.BillingCycle).HasMaxLength(20).HasDefaultValue("Monthly");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");

                entity.HasOne(d => d.SubscriptionPlan)
                    .WithMany(p => p.Subscriptions)
                    .HasForeignKey(d => d.SubscriptionPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.Subscriptions)
                    .HasForeignKey(d => d.CustomerId);

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Subscriptions)
                    .HasForeignKey(d => d.CompanyId);
            });
            #endregion

            #region SubscriptionPlan
            modelBuilder.Entity<SubscriptionPlan>(entity =>
            {
                entity.HasKey(e => e.SubscriptionPlanId);
                entity.Property(e => e.PlanName).HasMaxLength(100);
                entity.Property(e => e.Category).HasMaxLength(50);
                entity.Property(e => e.Description).HasMaxLength(500);
                entity.Property(e => e.Status).HasMaxLength(20).HasDefaultValue("Active");
                entity.Property(e => e.Benefits).HasMaxLength(500);
                entity.Property(e => e.PriceMonthly).HasColumnType("decimal(12,2)");
                entity.Property(e => e.PriceYearly).HasColumnType("decimal(12,2)");
                entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5,2)");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())").HasColumnType("datetime");
            });
            #endregion

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
