// <auto-generated>
// Updated by ChatGPT – Invoice model for monthly billing and session grouping
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models
{
    public partial class Invoice
    {
        public int InvoiceId { get; set; }

        public int? SubscriptionId { get; set; }   // Gói đăng ký (nếu có)
        public int CustomerId { get; set; }        // Bắt buộc: dùng để nhóm hóa đơn theo khách hàng

        public decimal? Subtotal { get; set; }
        public decimal? SubscriptionAdjustment { get; set; }
        public decimal? Tax { get; set; }
        public decimal? Total { get; set; }

        public int BillingMonth { get; set; }
        public int BillingYear { get; set; }
        public bool IsMonthlyInvoice { get; set; } = true;

        public string Status { get; set; } = "Unpaid"; // 'Unpaid', 'Paid', 'Overdue'
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        // Navigation
        public virtual Customer Customer { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
        public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
    }
}
