// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }
    public int ChargingSessionId { get; set; }

    public decimal? Subtotal { get; set; }
    public decimal? SubscriptionAdjustment { get; set; }
    public decimal? Tax { get; set; }
    public decimal? Total { get; set; }
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public string Status { get; set; }
    public int? SubscriptionId { get; set; }
    public int? BillingMonth { get; set; }
    public int? BillingYear { get; set; }
    public bool IsMonthlyInvoice { get; set; } = true;

    public virtual ChargingSession ChargingSession { get; set; }
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
   

    // Navigation
    public virtual Subscription Subscription { get; set; }

}
