// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Payment
{
    public int PaymentId { get; set; }
    public int? InvoiceId { get; set; } // Thanh toán trả sau
    public int? BookingId { get; set; } // Thanh toán trực tiếp
    public int? SubscriptionId { get; set; }   // ✅ Thêm dòng này
    public int? CompanyId { get; set; }        // ✅ Công ty thanh toán
    public int CustomerId { get; set; }
    public int? ChargingSessionId { get; set; }

    public string Method { get; set; }
    public decimal? Amount { get; set; }
    public DateTime? PaidAt { get; set; }
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public string Status { get; set; }
    public string? Description { get; set; }  // Mô tả giao dịch (vd: combo Invoice + Subscription)

    public virtual Customer Customer { get; set; }
    public virtual Company? Company { get; set; }
    public virtual Invoice Invoice { get; set; }
    public virtual Booking Booking { get; set; }
    public virtual Subscription Subscription { get; set; }  // ✅ Thêm dòng này
    public virtual ChargingSession? ChargingSession { get; set; }


}
