// <auto-generated>
// Updated by ChatGPT – PricingRule now applies per Charger type and power
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models
{
    public partial class PricingRule
    {
        public int PricingRuleId { get; set; }

        // Loại trụ sạc: "AC" / "DC"
        public string ChargerType { get; set; }

        // Công suất trụ: ví dụ 60, 120
        public decimal PowerKw { get; set; }

        // Khung giờ: "Low", "Normal", "Peak"
        public string TimeRange { get; set; }

        // Giá điện theo kWh
        public decimal PricePerKwh { get; set; }

        // Phí chờ mỗi phút sau khi sạc đầy
        public decimal IdleFeePerMin { get; set; }

        // "Active" | "Inactive"
        public string Status { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        // Navigation property
        public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
    }
}
