// <auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PricingRule
{
    public int PricingRuleId { get; set; }

    public string Name { get; set; } // Tên quy tắc giá
    public decimal RatePerKwh { get; set; } // VNĐ/kWh
    public decimal TaxRate { get; set; } // Ví dụ: 0.1 = 10%
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public string ConnectorType { get; set; } // AC / DC
    public int? StationId { get; set; } // Áp dụng cho trạm sạc cụ thể
    public string Status { get; set; } // Active / Inactive
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public virtual Station Station { get; set; }
    public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
}
