// <auto-generated>
// Updated by ChatGPT - Simplified PricingRule model for EV Charging
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models
{
    public partial class PricingRule
    {
        public int PricingRuleId { get; set; }

        public string VehicleType { get; set; }      // "Car" | "Motorbike"
        public string TimeRange { get; set; }        // "Low" | "Normal" | "Peak"
        public decimal PricePerKwh { get; set; }     // VNĐ / kWh
        public decimal IdleFeePerMin { get; set; }   // VNĐ / phút chờ sau khi sạc đầy
        public string Status { get; set; }           // "Active" | "Inactive"
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        // Navigation property
        public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();
    }
}
