// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Station
{
    public int StationId { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Charger> Chargers { get; set; } = new List<Charger>();
    public virtual ICollection<PricingRule> PricingRules { get; set; } = new HashSet<PricingRule>();

}