    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
    #nullable disable
    using System;
    using System.Collections.Generic;

    namespace Repositories.Models;

    public partial class Vehicle
    {
        public int VehicleId { get; set; }

        public int CustomerId { get; set; }

        public int? CompanyId { get; set; }

        public string CarMaker { get; set; }

        public string VehicleType { get; set; }  // "Xe máy" hoặc "Ô tô"
    
        public string Model { get; set; }

        public string LicensePlate { get; set; }

        public decimal? BatteryCapacity { get; set; }

        public int? CurrentSoc { get; set; }

        public string ConnectorType { get; set; }

        public int? ManufactureYear { get; set; }

        public DateTime? CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public string Status { get; set; }

        public string ImageUrl { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

        public virtual ICollection<ChargingSession> ChargingSessions { get; set; } = new List<ChargingSession>();

        public virtual Company Company { get; set; }

        public virtual Customer Customer { get; set; }
    }